- build: examples/1_SimpleGPS
  electron: [latest]
- build: examples/2_GPSCellularOnOff
  electron: [latest]
- build: examples/3_WakeOnMove
  electron: [latest]
- build: examples/4_AccelerometerSamples
  electron: [latest]
- build: examples/5_AccelerometerDirection
  electron: [latest]
- build: examples/6_BackwardCompatibleAPI
  photon: [latest]
  electron: [1.0.0, latest]
  argon: [0.9.0, latest]
  boron: [0.9.0, latest]
- build: examples/7_DataDump
  electron: [latest]
- build: examples/8_ThreadedMode
  electron: [latest]
  boron: [latest]
- build: examples/9_I2C
  electron: [1.0.0, latest]
  boron: [0.8.0-rc.27, latest]
- build: examples/10_PassThrough
  electron: [latest]
  boron: [latest]
- build: examples/11_AssistNowTest
  electron: [latest]
  boron: [latest]